try:
    Num=int(input())
    print(Num)
except Exception as e:
    print("ValueError",e)
